### PR TITLE
Little update GcodeCNCDemo2Axis.ino

### PR DESCRIPTION
**Pull request by lsahidin**
Hi,
After make a library for HG7881, I took a look on this code. and then add some little modification:
- call disable() function on line() function, this is affect for HG7881 driver to avoid produce more heat (to not drive the motor unnecessarily)
- on loop() function modified newline detection, because I try to enter gcode from terminal using putty but the machine didn't response. I did not yet using GcodeSender, but after change the code then it works

### CODE REVIEW

**Comment by i-make-robots** [comment]
Great patch!

Please remove the disable() and use M18 after your lines to reduce heat.  Don't change the behaviour for everyone else. :)

Great addition! I will put your name in the credits when you resubmit.

Dan

**Comment by lsahidin** [comment]
already change the behaviour back, I'm sorry if any revision unnecessary like "space" or "new line" on the code, I'm new on github :D and love it.
Thanks Dan.

Luqman

**Comment by lsahidin** [comment]
Thanks Dan.

Luqman

**Comment by i-make-robots** [comment]
I'm delighted you enjoy the project and look forward to your updated pull request.

**Comment by lsahidin** [comment]
Hi Dan, I have tried my code with HG7881 and it works. there my submit not yet complete? sorry to bother thanks.

**Comment by i-make-robots** [comment]
Apparently there are conflicts that prevent it from being automatically merged.  Can you resolve them?

**Comment by lsahidin** [comment]
Hi, I try to run command to resolve like rebase in Git shell but still didn't work. I think this is access, you ever get something like this issue?

**Comment by lsahidin** [comment]
warning message:
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

**Comment by i-make-robots** [comment]
I only get this when
- I pull
- someone else commits
- I commit

_boom_

On Sun, Aug 9, 2015 at 9:42 PM, Luqman Sahidin notifications@github.com
wrote:

> Hi, I try to run command to resolve like rebase in Git shell but still
> didn't work. I think this is access, you ever get something like this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarginallyClever/GcodeCNCDemo/pull/1#issuecomment-129297075
> .

## 

Dan Royer :: Marginally Clever http://www.marginallyclevergroup.com/ ::
Raising Robot Literacy :: +1.604.916.2281

**Pull request closed without merging**
