### PR TITLE
4-axis Arduino based CNC hot wire foam cutter

### PR DESCRIPTION
**Pull request by sorenvedel**
Hi Dan,

You are pulling me through new jungle here, but I hope everything is fine now. It is a very convenient tool, by the way. I can see that.

### CODE REVIEW

**Comment by i-make-robots** [comment]
You pull is good. Your changes are disruptive to anyone who uses axis 5 or 6 - it looks like you've removed them completely?  Maybe these changes should be in a new file, GcodeCNCDemo4AxisRAMPS.

**Comment by sorenvedel** [comment]
Yes I know I have changed a lot to achieve usage for my 4-axis hot wire cnc
foam cutter, but this is what I need for now.

I think it is a good idea to save it as a new file: GcodeCNCDemo4AxisRAMPS

Later I would like to add code for controlling the wire temperature
somehow. People tell me that this has not been done yet. Let's do it now!
:-)

Med venlig hilsen/Kind regards
Søren Vedel

2015-06-22 5:04 GMT-03:00 Dan Royer notifications@github.com:

**Comment by i-make-robots** [comment]
Can you resubmit this with the new filename so it doesn't step on the rumba file, please?

**Comment by sorenvedel** [comment]
HI Dan,

I tried to do something about it. Please check if it is better now? I am
really not used to do this kind of things.

Med venlig hilsen/Kind regards
Søren Vedel

2015-07-31 21:48 GMT-03:00 Dan Royer notifications@github.com:

**Comment by i-make-robots** [comment]
Great!  Thank you for your contribution.  You'll find I moved it to a folder with the same name as the original sketch file.

**Pull request merged**
